
FROM condaforge/mambaforge:24.3.0-0

# Install system dependencies including nginx and supervisor
RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    && rm -rf /var/lib/apt/lists/*

# Add a non-privileged user for nginx
RUN adduser --system --no-create-home --shell /bin/false --group --disabled-login nginx

# Copy environment.yaml
COPY environment.yaml /srv/shiny-server/environment.yaml

# Create the conda environment from the YAML file
RUN mamba env create -f /srv/shiny-server/environment.yaml

# Set the PATH to include the conda environment
ENV PATH /opt/conda/envs/merged_env/bin:$PATH

# Install R packages
RUN conda run -n merged_env R -e "install.packages('smplot2', repos='http://cran.rstudio.com/')"
RUN conda run -n merged_env R -e "install.packages('GOplot', repos='http://cran.rstudio.com/')"
RUN conda run -n merged_env R -e "install.packages('wordcloud2', repos='http://cran.rstudio.com/')"


RUN conda run -n merged_env R -e "devtools::install_github('cole-trapnell-lab/monocle3')"
RUN conda run -n merged_env R -e "devtools::install_github('mahmoudibrahim/genesorteR')"
RUN conda run -n merged_env R -e "remotes::install_github('satijalab/seurat-wrappers')"
RUN conda run -n merged_env R -e "remotes::install_github('daqana/dqshiny')"
RUN conda run -n merged_env R -e "install.packages('Seurat', repos ='http://cran.rstudio.com/')"

# Clean stale data
RUN conda clean -a -y


# animalcules
COPY animalcules  /srv/shiny-server/animalcules

# ATACseqQCShniy
COPY ATACseqQCShniy /srv/shiny-server/ATACseqQCShniy
COPY BSgenome.Hsapiens.UCSC.hg19_1.4.3.tar.gz /


# ClusterProfShinyGSEA
COPY ClusterProfShinyGSEA /srv/shiny-server/ClusterProfShinyGSEA

#ClusterProfShinyORA
COPY ClusterProfShinyORA /srv/shiny-server/ClusterProfShinyORA

#dada2Shiny
COPY dada2Shiny  /srv/shiny-server/dada2Shiny

#deseq2shiny
COPY deseq2shiny /srv/shiny-server/deseq2shiny

#debrowser
COPY DEBrowser /srv/shiny-server/DEBrowser


# GeneCountMerger
COPY GeneCountMerger /srv/shiny-server/GeneCountMerger


#monocle3
COPY monocle3 /srv/shiny-server/monocle3

#SeuratV5Shiny
COPY SeuratV5Shiny /srv/shiny-server/SeuratV5Shiny

#mergeFPKMs
COPY mergeFPKMs /srv/shiny-server/mergeFPKMs

#mergeFPKMs
COPY tsar_nasqar /srv/shiny-server/tsar_nasqar






# Copy your Shiny app files to the container

# Add Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf
COPY uiApp/src/out/ /usr/share/nginx/html



# Add the supervisor configuration file
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN sed -i 's|/opt/conda/envs/v_[^/ ]*|/opt/conda/envs/merged_env|g'  /etc/supervisor/conf.d/supervisord.conf

# Expose the port for the Nginx server
EXPOSE 80

# Command to start supervisord
CMD ["/usr/bin/supervisord"]
